import { ProductProps } from "../@types/product-props";

export const products: ProductProps[] = [
    {
        id: 1,
        name: "Camiseta",
        price: 19.99,
        userId: 2,
        user: {
            id: 2,
            name: "Amazon",
            email: "teste@gmail.com",
            createdAt: new Date(),
        },
        brandId: 3,
        brand: {
            id: 3,
            name: "Nike",
            userId: 2,
        },
    },
    { id: 2, name: "Calça Jeans", price: 39.99, userId: 2 },
    { id: 3, name: "Tênis", price: 59.99, userId: 2 },
    { id: 4, name: "Boné", price: 14.99, userId: 2 },
    { id: 5, name: "Mochila", price: 29.99, userId: 2 },
    { id: 6, name: "Relógio", price: 79.99, userId: 2 },
    { id: 7, name: "Óculos de Sol", price: 24.99, userId: 2 },
    { id: 8, name: "Bolsa", price: 49.99, userId: 2 },
    { id: 9, name: "Chapéu", price: 18.99, userId: 2 },
    { id: 10, name: "Sapato Social", price: 69.99, userId: 2 },
    { id: 11, name: "Caneca", price: 9.99, userId: 2 },
    { id: 12, name: "Colar", price: 34.99, userId: 2 },
    {
        id: 13,
        name: "Luvas",
        price: 12.99,
        userId: 2,
        brand: { id: 1, name: "De pedreiro", userId: 1 },
    },
    { id: 14, name: "Meias", price: 6.99, userId: 2 },
    { id: 15, name: "Cinto", price: 15.99, userId: 2 },
    { id: 16, name: "Pulseira", price: 8.99, userId: 2 },
    { id: 17, name: "Blusa de Frio", price: 29.99, userId: 2 },
    { id: 18, name: "Shorts", price: 22.99, userId: 2 },
    { id: 19, name: "Caneta", price: 2.99, userId: 2 },
    { id: 20, name: "Agenda", price: 16.99, userId: 2 },
];
